version: '3.1'

services:
  db:
    image: mysql
    container_name: desafio_jr_simplify_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - igoreason_data:/var/lib/mysql

volumes:
  igoreason_data: